import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { isSouthernZone } from '../site/src/coords.js';
import { SOUTHERN_ZONES, TZDB_VERSION } from '../site/src/data/southern-zones.js';

// THE EXAMPLE IN THE HAND-ENTRY BOXES COMES FROM YOUR HEMISPHERE.
//
// "make default for southern Sydney AU". Before anyone gives a position the
// boxes are prefilled with an example, and a Texas example handed to someone
// in Sydney is a trap: press Apply and every number is northern, Polaris and
// all. The device's time zone picks the example -- Sydney for a southern zone,
// Kingwood otherwise -- read on the phone, with no permission and no network.

const app = readFileSync(fileURLToPath(new URL('../site/src/app.js', import.meta.url)), 'utf8');

test('southern time zones are recognised, by their current and their old names', () => {
  for (const z of ['Australia/Sydney', 'Australia/NSW', 'Pacific/Auckland', 'America/Sao_Paulo',
    'America/Argentina/Buenos_Aires', 'America/Buenos_Aires', 'America/Santiago', 'America/Lima',
    'Africa/Johannesburg', 'Asia/Jakarta']) {
    assert.ok(isSouthernZone(z), `${z} is south of the equator`);
  }
  // Reunion is filed under Dubai in zone1970.tab; phones still report it by
  // name, and it is in the south Indian Ocean.
  assert.ok(isSouthernZone('Indian/Reunion'));
});

test('northern, unknown and missing zones keep the northern example', () => {
  for (const z of ['America/Chicago', 'Europe/London', 'Asia/Calcutta', 'Asia/Kolkata', 'Asia/Dubai',
    'Asia/Singapore', 'America/Bogota', 'UTC', 'Etc/GMT+5', 'Not/AZone', '', undefined, null]) {
    assert.equal(isSouthernZone(z), false, `${z} is not a southern zone`);
  }
});

test('the zone list is generated from the time zone database, and says from which release', () => {
  assert.match(TZDB_VERSION, /^20\d\d[a-z]$/);
  assert.ok(SOUTHERN_ZONES.size > 100, `${SOUTHERN_ZONES.size} zones looks too few`);
  const src = readFileSync(fileURLToPath(new URL('../site/src/data/southern-zones.js', import.meta.url)), 'utf8');
  assert.match(src, /^\/\/ GENERATED by scripts\/build-southern-zones\.py/);
});

test('the boxes are prefilled from this device\'s hemisphere, and still never applied on their own', () => {
  assert.match(app, /const SOUTHERN_DEFAULT_SITE = \{ name: 'Sydney, Australia', lat: -33\.8721, lon: 151\.2044, altitude: 59 \};/);
  assert.match(app, /const DEFAULT_SITE = \{ name: 'Kingwood, Texas', lat: 30\.0563, lon: -95\.2107, altitude: 26 \};/);
  const fn = app.slice(app.indexOf('function exampleSite()'), app.indexOf('\n}', app.indexOf('function exampleSite()')));
  assert.match(fn, /Intl\.DateTimeFormat\(\)\.resolvedOptions\(\)\.timeZone/);
  assert.match(fn, /isSouthernZone\(zone\) \? SOUTHERN_DEFAULT_SITE : DEFAULT_SITE/);
  assert.match(fn, /try \{/, 'a browser without Intl must not break the form');
  assert.match(app, /const from = site \|\| exampleSite\(\);/);
  // Used to fill the boxes, never handed to setSite: one call site only.
  assert.equal((app.match(/exampleSite\(\)/g) || []).length, 2, 'defined once, used once (the prefill)');
  assert.match(app, /`Filled in with \$\{from\.name\} as a starting point/);
});
