#!/usr/bin/env python3
# evomedia.net evo.polaris — https://github.com/evomedia-net/evo.polaris
# Created by Kelly Michels · dev@evomedia.net
# Licensed under the MIT License. See LICENSE.

"""
Write site/src/data/southern-zones.js: the IANA time zones whose location is
south of the equator.

WHY THIS EXISTS. The hand-entry boxes are prefilled with an example position
before anyone has given theirs, and an example from the wrong hemisphere is a
trap: a first-time visitor in Sydney who presses Apply on a Texas example gets
a northern solution, Polaris and all. The device's time zone says which
hemisphere to show an example from without asking for location, without the
network, and without anything leaving the phone.

WHY zone.tab AND NOT zone1970.tab. zone1970.tab merges zones that have kept
the same clocks since 1970, across borders: Indian/Reunion is filed under
Asia/Dubai, at Dubai's coordinates. Phones still report "Indian/Reunion", and
zone.tab still lists it at its own coordinates, south of the equator.

WHY THE backward LINKS. Browsers report some zones by their old names --
"America/Buenos_Aires" rather than "America/Argentina/Buenos_Aires" -- so every
old name that links to a southern zone is listed too.

    python scripts/build-southern-zones.py
"""
from __future__ import annotations

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "site" / "src" / "data" / "southern-zones.js"
BASE = "https://data.iana.org/time-zones/tzdb/"


def fetch(name: str) -> str:
    with urllib.request.urlopen(BASE + name, timeout=30) as r:
        return r.read().decode("utf-8")


def latitude(iso6709: str) -> float:
    """The latitude half of a zone.tab coordinate: +DDMM or +DDMMSS."""
    m = re.match(r"([+-])(\d{2})(\d{2})(\d{2})?", iso6709)
    sign, deg, mins, secs = m.group(1), int(m.group(2)), int(m.group(3)), int(m.group(4) or 0)
    value = deg + mins / 60 + secs / 3600
    return -value if sign == "-" else value


def main() -> None:
    version = fetch("version").strip()
    zones: dict[str, float] = {}
    for line in fetch("zone.tab").splitlines():
        if not line or line.startswith("#"):
            continue
        _cc, coord, name = line.split("\t")[:3]
        zones[name] = latitude(coord)

    southern = {name for name, lat in zones.items() if lat < 0}
    for line in fetch("backward").splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[0] == "Link":
            target, alias = parts[1], parts[2]
            # An old name for a southern zone -- unless zone.tab places the old
            # name itself, which wins (the Reunion case, the other way round).
            if target in southern and alias not in zones:
                southern.add(alias)

    names = sorted(southern)
    body = ",\n".join(f"  '{n}'" for n in names)
    OUT.write_text(
        "// evomedia.net evo.polaris — https://github.com/evomedia-net/evo.polaris\n"
        "// Created by Kelly Michels · dev@evomedia.net\n"
        "// The code is MIT-licensed (see LICENSE). The data's source and terms are named below and in README.md.\n"
        "\n"
        "// GENERATED by scripts/build-southern-zones.py from IANA tzdb "
        f"{version} (zone.tab + backward) -- do not edit by hand.\n"
        "//\n"
        "// Time zones whose location is south of the equator, by their current and\n"
        "// their old names. Used only to choose which example position prefills\n"
        "// the hand-entry boxes; nothing is sent anywhere.\n"
        f"export const TZDB_VERSION = '{version}';\n"
        f"export const SOUTHERN_ZONES = new Set([\n{body},\n]);\n",
        encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(names)} southern zones from tzdb {version}")


if __name__ == "__main__":
    main()
