#!/usr/bin/env python3
# evomedia.net evo.polaris — https://github.com/evomedia-net/evo.polaris
# Created by Kelly Michels · dev@evomedia.net
# Licensed under the MIT License. See LICENSE.

"""Generate the app's runtime data from public-domain source catalogs.

Inputs (fetched by scripts/fetch-sources.sh, not committed):
    scripts/bsc5.dat   Yale Bright Star Catalog, VizieR V/50
    scripts/WMM.COF    NOAA World Magnetic Model 2025 coefficients

Outputs (committed -- these are what the app loads):
    src/data/stars.json    compact star list for the sky chart
    src/data/wmm2025.js    WMM coefficients, verbatim, as an ES module

Run: python scripts/build-data.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "site", "src", "data")


def col(line, a, b):
    """1-indexed inclusive fixed-width slice."""
    return line[a - 1:b]


def num(s, default=None):
    s = s.strip()
    if not s:
        return default
    try:
        return float(s)
    except ValueError:
        return default


def build_stars():
    """Yale BSC5 -> [ra_deg, dec_deg, vmag, bv, hr, name] sorted brightest first.

    Column positions are from the VizieR V/50 ReadMe. We take the J2000
    position (cols 76-90), not the B1900 one that precedes it.
    """
    src = os.path.join(HERE, "bsc5.dat")
    if not os.path.exists(src):
        sys.exit("missing scripts/bsc5.dat -- run scripts/fetch-sources.sh first")

    stars, skipped = [], 0
    with open(src, "r", encoding="latin-1") as fh:
        for line in fh:
            if len(line) < 107:
                skipped += 1
                continue
            rah = num(col(line, 76, 77))
            ram = num(col(line, 78, 79))
            ras = num(col(line, 80, 83))
            sign = col(line, 84, 84)
            ded = num(col(line, 85, 86))
            dem = num(col(line, 87, 88))
            des = num(col(line, 89, 90))
            vmag = num(col(line, 103, 107))
            if None in (rah, ram, ras, ded, dem, des) or vmag is None:
                skipped += 1          # novae and a few entries carry no position
                continue

            ra = (rah + ram / 60.0 + ras / 3600.0) * 15.0
            dec = ded + dem / 60.0 + des / 3600.0
            if sign == "-":
                dec = -dec
            bv = num(col(line, 110, 114))

            stars.append([
                round(ra, 4), round(dec, 4), round(vmag, 2),
                round(bv, 2) if bv is not None else 0.0,
                int(col(line, 1, 4)), col(line, 5, 14).strip(),
            ])

    stars.sort(key=lambda s: s[2])
    path = os.path.join(OUT, "stars.json")
    with open(path, "w") as fh:
        json.dump(stars, fh, separators=(",", ":"))
    print(f"stars.json   {len(stars):5d} stars, {skipped} skipped, "
          f"{os.path.getsize(path)/1024:.0f} KB")


def build_wmm():
    """Embed WMM.COF verbatim so provenance stays auditable in the repo."""
    src = os.path.join(HERE, "WMM.COF")
    if not os.path.exists(src):
        sys.exit("missing scripts/WMM.COF -- run scripts/fetch-sources.sh first")

    with open(src, "r") as fh:
        text = fh.read()
    if "`" in text or "${" in text:
        sys.exit("COF contains template-literal metacharacters; escape needed")

    epoch = text.strip().splitlines()[0].split()[0]
    path = os.path.join(OUT, "wmm2025.js")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(
            "// evomedia.net evo.polaris — https://github.com/evomedia-net/evo.polaris\n"
            "// Created by Kelly Michels · dev@evomedia.net\n"
            "// The code is MIT-licensed (see LICENSE). The data's source and terms are named below and in README.md.\n"
            "\n"
            "// GENERATED by scripts/build-data.py -- do not edit.\n"
            "// NOAA/NCEI World Magnetic Model 2025 coefficients, verbatim.\n"
            "// Source: https://www.ncei.noaa.gov/products/world-magnetic-model\n"
            "// US Government work, public domain. Valid 2025.0 through 2030.0.\n"
            f"export const WMM_EPOCH = {epoch};\n"
            "export const WMM_COF = `" + text + "`;\n"
        )
    print(f"wmm2025.js   epoch {epoch}, {os.path.getsize(path)} bytes")


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    build_stars()
    build_wmm()
