/**
 * Read or bump this project's version stamp.
 *
 * Scheme: v{major}.{rc}.{beta}.{alpha}.{build} -- priority left to right.
 * Bumping a stage zeroes every lower segment, build included. This project is
 * ALPHA, so it sits at v0.0.0.1.{build} and only the build counter moves in
 * normal work.
 *
 *   node scripts/bump-version.mjs get
 *   node scripts/bump-version.mjs bump                 # build + 1
 *   node scripts/bump-version.mjs bump-stage <stage>   # release|rc|beta|alpha
 *   node scripts/bump-version.mjs tag-command
 *
 * THE BUILD COUNTER ADVANCES ONCE PER RELEASE, not per merged PR. A release
 * carrying five PRs moves it by one, because the number names a thing that
 * SHIPPED. It is stamped on the default branch after the merge, never inside a
 * feature PR, so concurrent PRs cannot conflict on it.
 *
 * WHY THIS WRITES THREE FILES. The stamp has to be in three places and they
 * have to agree, so one command writes all three and a test refuses to let
 * them drift:
 *
 *   build-version.json       the source of truth; what zdeploy packs against
 *   site/build-version.json  the SERVED copy -- only site/ is deployed, so a
 *                            stamp outside it is a stamp nobody can check
 *   site/src/version.js      what the app itself shows, as a module, so the
 *                            footer needs no fetch and is right offline
 *
 * That third file is why the version was wrong for this project's whole life:
 * the footer carried a hand-typed "v0.0.0.1.0" that no bump could ever reach.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(ROOT, 'build-version.json');
const SERVED = join(ROOT, 'site', 'build-version.json');
const MODULE = join(ROOT, 'site', 'src', 'version.js');

const STAGES = ['major', 'rc', 'beta', 'alpha', 'build'];

export function parse(version) {
  const parts = String(version).replace(/^v/, '').split('.').map(Number);
  if (parts.length !== 5 || parts.some((n) => !Number.isInteger(n) || n < 0)) {
    throw new Error(`not a 5-segment version: ${version}`);
  }
  return Object.fromEntries(STAGES.map((k, i) => [k, parts[i]]));
}

export const label = (v) => `v${STAGES.map((k) => v[k]).join('.')}`;

/** Bumping a stage zeroes every lower one. Release is major + 1. */
export function bumpStage(v, stage) {
  const i = stage === 'release' ? 0 : STAGES.indexOf(stage);
  if (i < 0) throw new Error(`unknown stage: ${stage}`);
  const out = { ...v };
  out[STAGES[i]] += 1;
  for (let j = i + 1; j < STAGES.length; j++) out[STAGES[j]] = 0;
  return out;
}

function read() {
  return parse(JSON.parse(readFileSync(SOURCE, 'utf8')).version);
}

function write(v, stage) {
  const version = label(v).slice(1);
  const doc = {
    version,
    stage,
    scheme: 'v{major}.{rc}.{beta}.{alpha}.{build}',
    note: 'Build advances once per release on the default branch, never inside a PR.',
  };
  const json = `${JSON.stringify(doc, null, 2)}\n`;
  writeFileSync(SOURCE, json);
  // The served copy is byte-identical: zdeploy compares the label it packed
  // against the one the site hands back, and two files that could differ is
  // two files that eventually will.
  writeFileSync(SERVED, json);
  writeFileSync(MODULE,
    '// GENERATED by scripts/bump-version.mjs -- do not edit by hand.\n'
    + '//\n'
    + '// The app shows its own version from here rather than fetching the\n'
    + '// JSON, so the footer is right with the radio off like everything else.\n'
    + `export const VERSION = '${label(v)}';\n`);
  return label(v);
}

const [cmd, arg] = process.argv.slice(2);
const current = read();
const stage = JSON.parse(readFileSync(SOURCE, 'utf8')).stage || 'alpha';

if (cmd === 'get') {
  process.stdout.write(`${label(current)}\n`);
} else if (cmd === 'bump') {
  process.stdout.write(`${write(bumpStage(current, 'build'), stage)}\n`);
} else if (cmd === 'bump-stage') {
  const next = arg === 'release' ? 'released' : arg;
  process.stdout.write(`${write(bumpStage(current, arg), next)}\n`);
} else if (cmd === 'tag-command') {
  const l = label(current);
  process.stdout.write(`git tag -a ${l} -m "${l}" && git push --follow-tags\n`);
} else if (cmd) {
  process.stderr.write('usage: get | bump | bump-stage <stage> | tag-command\n');
  process.exit(1);
}
